# Generated by Django 2.2.6 on 2020-01-08 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ikigai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('idhora', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idhorario', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=2)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idreserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('idbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ikigai.Box')),
                ('idusuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorasReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idhora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserva.Hora')),
                ('idreserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.Reserva')),
            ],
        ),
        migrations.AddField(
            model_name='hora',
            name='idhorario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserva.Horario'),
        ),
    ]
