# Generated by Django 2.2.6 on 2019-11-05 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ikigai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('idHora', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('idBox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ikigai.Box')),
                ('idUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorasReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserva.Hora')),
                ('idReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.Reserva')),
            ],
        ),
        migrations.AddField(
            model_name='hora',
            name='idHorario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserva.Horario'),
        ),
    ]
