# Generated by Django 2.2.6 on 2020-01-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasReservadas',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
            ],
            options={
                'db_table': 'reserva_horasreservadas',
                'managed': False,
            },
        ),
    ]
